
package require psfgen 
topology lignin.top 	 
set outputname test ;#set variable variablename


;# build the monomer iteratively: First iteration
set count 4 
 resetpsf
 segment  li {
  residue 1 GUAI
  residue 2 GUAI
  residue 3 SYR
  residue 4 GUAI
}

patch bO4L  li:1  li:2 ;# bO4 --> I
patch bO4R  li:2  li:3
patch bO4L  li:3  li:4
regenerate angles dihedrals
coordpdb G-bO4L-G.pdb li ;# different in first iteration compared to the subsequent ones ## open a pdb file with coordinates of a dimer
guesscoord ;## this will guess the rest of the coordinates --> can create steric clashes.. because it is done blindly --> reason of doing it iteratively	 
writepdb $outputname.pdb	 
writepsf $outputname.psf
;#exit

namd2 mini.conf > mini.out

;#exit


;# build the monomer iteratively: Second iteration
set count 8 
 resetpsf
 segment  li {
  residue 1 GUAI
  residue 2 GUAI
  residue 3 SYR
  residue 4 GUAI
  residue 5 SYR
  residue 6 SYR
  residue 7 GUAI
  residue 8 GUAI
}

patch bO4L  li:1  li:2 ;# bO4 --> I
patch bO4R  li:2  li:3
patch bO4L  li:3  li:4
patch bO4R   li:4  li:5 ;# bb --> III
patch bO4L  li:5  li:6
patch bO4R  li:6  li:7
patch b5L   li:7  li:8 ;# b5 --> II
regenerate angles dihedrals
coordpdb $outputname.coor li ;# name.coor is a pdb file generated by namd after the minimization
guesscoord ;## this will guess the rest of the coordinates --> can create steric clashes.. because it is done blindly --> reason of doing it iteratively	 
writepdb $outputname.pdb	 
writepsf $outputname.psf
;#exit

namd2 mini.conf > mini.out
;#exit

;# build the monomer iteratively: Third iteration
set count 13 
 resetpsf
 segment  li {
  residue 1 GUAI
  residue 2 GUAI
  residue 3 SYR
  residue 4 GUAI
  residue 5 SYR
  residue 6 SYR
  residue 7 GUAI
  residue 8 GUAI
  residue 9 GUAI
  residue 10 SYR
  residue 11 GUAI
  residue 12 GUAI
  residue 13 SYR
}

patch bO4L  li:1  li:2 ;# bO4 --> I
patch bO4R  li:2  li:3
patch bO4L  li:3  li:4
patch bO4R   li:4  li:5 ;# bb --> III
patch bO4L  li:5  li:6
patch bO4R  li:6  li:7
patch b5L   li:7  li:8 ;# b5 --> II
patch b5R  li:8  li:9
patch bO4L  li:9  li:10
patch bO4R  li:10 li:11 
patch b5R   li:11 li:12
patch bO4L  li:12 li:13
regenerate angles dihedrals
coordpdb $outputname.coor li ;# name.coor is a pdb file generated by namd after the minimization
guesscoord ;## this will guess the rest of the coordinqtes --> can create steric clashes.. because it is done blindly --> reason of doing it iteratively	 
writepdb $outputname.pdb	 
writepsf $outputname.psf
namd2 mini.conf > mini.out


;# build the monomer iteratively: Fourth iteration
set count 19 
 resetpsf
 segment  li {
  residue 1 GUAI
  residue 2 GUAI
  residue 3 SYR
  residue 4 GUAI
  residue 5 SYR
  residue 6 SYR
  residue 7 GUAI
  residue 8 GUAI
  residue 9 GUAI
  residue 10 SYR
  residue 11 GUAI
  residue 12 GUAI
  residue 13 SYR
  residue 14 GUAI
  residue 15 GUAI
  residue 16 GUAI
  residue 17 GUAI
  residue 18 SYR
  residue 19 GUAI
}

patch bO4L  li:1  li:2 ;# bO4 --> I
patch bO4R  li:2  li:3
patch bO4L  li:3  li:4
patch bO4R   li:4  li:5 ;# bb --> III
patch bO4L  li:5  li:6
patch bO4R  li:6  li:7
patch b5L   li:7  li:8 ;# b5 --> II
patch b5R  li:8  li:9
patch bO4L  li:9  li:10
patch bO4R  li:10 li:11 
patch b5R   li:11 li:12
patch bO4L  li:12 li:13
patch bO4R  li:13 li:14
patch bO4L  li:14 li:15
patch bO4R   li:15 li:16
patch bO4L  li:16 li:17
patch bO4R  li:17 li:18
patch bb   li:18 li:19
regenerate angles dihedrals
coordpdb $outputname.coor li ;# name.coor is a pdb file generated by namd after the minimization
guesscoord ;## this will guess the rest of the coordinates --> can create steric clashes.. because it is done blindly --> reason of doing it iteratively	 
writepdb $outputname.pdb	 
writepsf $outputname.psf
namd2 mini.conf > mini.out




exit
